# Generated by Django 3.2.8 on 2021-10-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_living', models.FloatField()),
                ('safety_index', models.FloatField()),
                ('climate_index', models.FloatField()),
                ('healthcare_index', models.FloatField()),
                ('city_name', models.CharField(max_length=200)),
            ],
        ),
    ]
