# Generated by Django 3.2.8 on 2021-11-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoliServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='healthcare_index',
            new_name='health_care_index',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='pollution_index',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='property_price_to_income_ratio',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='purchasing_power_index',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='traffic_commute_time_index',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
